global:
  scrape_interval: 15s
  external_labels:
    monitor: 'prometheus'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
        - targets: ['172.31.76.108:9090','172.31.38.60:9100','172.31.41.7:9100']
